### ISSUE TITLE
Shading messes with Stackmap frames

### ISSUE THREAD

**Issue by mlangc** [sbt/sbt-assembly#205]
I have

``` scala
assemblyShadeRules in assembly := Seq(
  ShadeRule.rename("akka.actor.ActorSystem" -> "akka.actor.MyVeryOwnActorSystem").inAll
)
```

Unfortunately, I get

```
Exception in thread "main" java.lang.VerifyError: Inconsistent stackmap frames at branch target 152
Exception Details:
  Location:
    akka/dispatch/Mailbox.processAllSystemMessages()V @152: getstatic
  Reason:
    Type top (current frame, locals[9]) is not assignable to 'akka/dispatch/sysmsg/SystemMessage' (stack map, locals[9])
  Current Frame:
    bci: @131
    flags: { }
    locals: { 'akka/dispatch/Mailbox', 'java/lang/InterruptedException', 'akka/dispatch/sysmsg/SystemMessage', top, 'akka/dispatch/Mailbox', 'java/lang/Throwable', 'java/lang/Throwable' }
    stack: { integer }
  Stackmap Frame:
    bci: @152
    flags: { }
    locals: { 'akka/dispatch/Mailbox', 'java/lang/InterruptedException', 'akka/dispatch/sysmsg/SystemMessage', top, 'akka/dispatch/Mailbox', 'java/lang/Throwable', 'java/lang/Throwable', top, top, 'akka/dispatch/sysmsg/SystemMessage' }
    stack: { }
  Bytecode:
    0x0000000: 014c 2ab2 0132 b601 35b6 0139 4db2 013e
    0x0000010: 2cb6 0142 9900 522a b600 c69a 004b 2c4e
    0x0000020: b201 3e2c b601 454d 2db9 0148 0100 2ab6
    0x0000030: 0052 2db6 014b b801 0999 000e bb00 e759
    0x0000040: 1301 4db7 010f 4cb2 013e 2cb6 0150 99ff
    0x0000050: bf2a b600 c69a ffb8 2ab2 0132 b601 35b6
    0x0000060: 0139 4da7 ffaa 2ab6 0052 b600 56b6 0154
    0x0000070: b601 5a3a 04a7 0091 3a05 1905 3a06 1906
    0x0000080: c100 e799 0015 1906 c000 e73a 0719 074c
    0x0000090: b200 f63a 08a7 0071 b201 5f19 06b6 0163
    0x00000a0: 3a0a 190a b601 6899 0006 1905 bf19 0ab6
    0x00000b0: 016c c000 df3a 0b2a b600 52b6 0170 b601
    0x00000c0: 76bb 000f 5919 0b2a b600 52b6 017a b601
    0x00000d0: 80b6 0186 2ab6 018a bb01 8c59 b701 8e13
    0x00000e0: 0190 b601 9419 09b6 0194 1301 96b6 0194
    0x00000f0: 190b b601 99b6 0194 b601 9ab7 019d b601
    0x0000100: a3b2 00f6 3a08 b201 3e2c b601 4299 0026
    0x0000110: 2c3a 09b2 013e 2cb6 0145 4d19 09b9 0148
    0x0000120: 0100 1904 2ab6 0052 b601 7a19 09b6 01a7
    0x0000130: a7ff d62b c600 09b8 0109 572b bfb1     
  Exception Handler Table:
    bci [290, 307] => handler: 120
  Stackmap Table:
    append_frame(@13,Object[#231],Object[#177])
    append_frame(@71,Object[#177])
    chop_frame(@102,1)
    full_frame(@120,{Object[#2],Object[#231],Object[#177],Top,Object[#2],Object[#177]},{Object[#223]})
    full_frame(@152,{Object[#2],Object[#231],Object[#177],Top,Object[#2],Object[#223],Object[#223],Top,Top,Object[#177]},{})
    append_frame(@173,Object[#357])
    full_frame(@262,{Object[#2],Object[#231],Object[#177],Top,Object[#2]},{})
    same_frame(@307)
    same_frame(@317)

    at akka.dispatch.Mailboxes.<init>(Mailboxes.scala:33)
    at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:638)
    at akka.actor.ActorSystem$.apply(ActorSystem.scala:141)
    at akka.actor.ActorSystem$.apply(ActorSystem.scala:108)
    at at.irian.bibi.util.concurrent.akka.DefaultAkkaSupport$.<init>(BasicAkkaSupport.scala:29)
```

when trying to run the application. I also tried the rule

``` scala
assemblyShadeRules in assembly := Seq(
  ShadeRule.rename("akka.actor.ActorSystem*" -> "akka.actor.MyVeryOwnActorSystem@1").inAll
)
```

but this resulted in a similar error. Is it not possible to rename single classes? I would rename the entire `akka` package, but then I'm affected by #173.

**Comment by eed3si9n** [comment]
The sbt-assembly issue tracker is not a support system. Please open a stackoverflow question to get help.

**Comment by mlangc** [comment]
This isn't a support question either; it's a bug!

**Comment by mlangc** [comment]
Or do you consider a `java.lang.VerifyError` to be a feature?

**Comment by adeandrade** [comment]
+1

**Comment by jrudolph** [comment]
Let's reopen. This is a bug that needs to be fixed. It can be easily reproduced by using assembly on a project which uses akka and adding an arbitrary shading rule.

**Comment by jrudolph** [comment]
Here's the difference between the two stackmaps:

original:

```
      StackMapTable: number_of_entries = 9
        frame_type = 253 /* append */
          offset_delta = 13
          locals = [ class java/lang/InterruptedException, class akka/dispatch/sysmsg/SystemMessage ]
        frame_type = 252 /* append */
          offset_delta = 57
          locals = [ class akka/dispatch/sysmsg/SystemMessage ]
        frame_type = 250 /* chop */
          offset_delta = 30
        frame_type = 255 /* full_frame */
          offset_delta = 17
          locals = [ class akka/dispatch/Mailbox, class java/lang/InterruptedException, class akka/dispatch/sysmsg/SystemMessage, top, class akka/dispatch/Mailbox, class akka/dispatch/sysmsg/SystemMessage ]
          stack = [ class java/lang/Throwable ]
        frame_type = 253 /* append */
          offset_delta = 31
          locals = [ class java/lang/Throwable, class java/lang/Throwable ]
        frame_type = 254 /* append */
          offset_delta = 20
          locals = [ top, top, class scala/Option ]
        frame_type = 255 /* full_frame */
          offset_delta = 88
          locals = [ class akka/dispatch/Mailbox, class java/lang/InterruptedException, class akka/dispatch/sysmsg/SystemMessage, top, class akka/dispatch/Mailbox ]
          stack = []
        frame_type = 44 /* same */
        frame_type = 9 /* same */
```

after shading:

```
      StackMapTable: number_of_entries = 9
        frame_type = 253 /* append */
          offset_delta = 13
          locals = [ class java/lang/InterruptedException, class akka/dispatch/sysmsg/SystemMessage ]
        frame_type = 252 /* append */
          offset_delta = 57
          locals = [ class akka/dispatch/sysmsg/SystemMessage ]
        frame_type = 250 /* chop */
          offset_delta = 30
        frame_type = 255 /* full_frame */
          offset_delta = 17
          locals = [ class akka/dispatch/Mailbox, class java/lang/InterruptedException, class akka/dispatch/sysmsg/SystemMessage, top, class akka/dispatch/Mailbox, class akka/dispatch/sysmsg/SystemMessage ]
          stack = [ class java/lang/Throwable ]
        frame_type = 255 /* full_frame */
          offset_delta = 31
          locals = [ class akka/dispatch/Mailbox, class java/lang/InterruptedException, class akka/dispatch/sysmsg/SystemMessage, top, class akka/dispatch/Mailbox, class java/lang/Throwable, class java/lang/Throwable, top, top, class akka/dispatch/sysmsg/SystemMessage ]
          stack = []
        frame_type = 252 /* append */
          offset_delta = 20
          locals = [ class scala/Option ]
        frame_type = 255 /* full_frame */
          offset_delta = 88
          locals = [ class akka/dispatch/Mailbox, class java/lang/InterruptedException, class akka/dispatch/sysmsg/SystemMessage, top, class akka/dispatch/Mailbox ]
          stack = []
        frame_type = 44 /* same */
        frame_type = 9 /* same */
```

I think there are several problems here:
 * a class not affected by shading shouldn't be rewritten in the first place
 * a bug in jarjar or even ASM in generating valid StackMapTables

**Comment by pomadchin** [comment]
Sorry that I'm throwing you another report about this issue; Example mini project: https://github.com/pomadchin/shading-issue 

It's [build.sbt](https://github.com/pomadchin/shading-issue/blob/master/build.sbt):
```scala
name := "shading-issue"
version := "0.1.0-SNAPSHOT"
scalaVersion := "2.11.8"
crossScalaVersions := Seq("2.12.0", "2.11.8")
organization := "com.azavea"
scalacOptions ++= Seq(
  "-deprecation",
  "-unchecked",
  "-Yinline-warnings",
  "-language:implicitConversions",
  "-language:reflectiveCalls",
  "-language:higherKinds",
  "-language:postfixOps",
  "-language:existentials",
  "-feature"
)

libraryDependencies ++= Seq(
  "com.typesafe.akka" %% "akka-actor" % "2.5-M1",
  "com.github.scopt" %% "scopt" % "3.5.0" // random library to shade (has no transitive deps)
)

// Since Akka 2.4-M1 stackmap issue would appear: (2.3.16 would work with shading)
assemblyShadeRules in assembly := {
  val shadePackage = "com.azavea.shaded.demo"
  Seq(
    ShadeRule.rename("com.github.scopt.**" -> s"$shadePackage.com.github.scopt.@1").inAll
  )
}

test in assembly := {}
```

**Comment by karol-brejna-i** [comment]
We had similar problem in Gearpump (https://issues.apache.org/jira/browse/GEARPUMP-236)

Forcing the project to use asm v. 5.1 seemed to solve the problem.

I tried the same with https://github.com/pomadchin/shading-issue but it didn't help.
Need to recheck.

**Comment by pomadchin** [comment]
@karol-brejna-i indeed asm bug, helped to rebuild sbt-assembly plugin with new asm dep
