### ISSUE TITLE
Running on Windows will result in case leaks.

### ISSUE THREAD

**Issue by jkugiya** [sbt/sbt-assembly#297]
In the following setting, I got deduplicate error.

setting:
```scala
      assemblyMergeStrategy in assembly := {
        case "META-INF/io.netty.versions.properties" =>
          MergeStrategy.first
        case "ahc-default.properties" =>
          ahcMerge
        case x =>
          val oldStrategy = (assemblyMergeStrategy in assembly).value
          oldStrategy(x)
      },
```

error:
```
[error] java.lang.RuntimeException: deduplicate: different file contents found in the following:
[error] C:\${user.dir}\.ivy2\cache\io.netty\netty-buffer\jars\netty-buffer-4.0.48.Final.jar:META-INF/io.netty.versions.properties
[error] C:\${user.dir}\.ivy2\cache\io.netty\netty-common\jars\netty-common-4.0.48.Final.jar:META-INF/io.netty.versions.properties
[error] C:\${user.dir}\.ivy2\cache\io.netty\netty-codec-http\jars\netty-codec-http-4.0.48.Final.jar:META-INF/io.netty.versions.properties
[error] C:\${user.dir}\.ivy2\cache\io.netty\netty-codec\jars\netty-codec-4.0.48.Final.jar:META-INF/io.netty.versions.properties
[error] C:\${user.dir}\.ivy2\cache\io.netty\netty-transport\jars\netty-transport-4.0.48.Final.jar:META-INF/io.netty.versions.properties
[error] C:\${user.dir}\.ivy2\cache\io.netty\netty-handler\jars\netty-handler-4.0.48.Final.jar:META-INF/io.netty.versions.properties
[error] C:\${user.dir}\.ivy2\cache\io.netty\netty-transport-native-epoll\jars\netty-transport-native-epoll-4.0.48.Final-linux-x86_64.jar:META-INF/io.netty.versions.properties
[error]         at sbtassembly.Assembly$.applyStrategies(Assembly.scala:142)
[error]         at sbtassembly.Assembly$.x$1$lzycompute$1(Assembly.scala:26)
[error]         at sbtassembly.Assembly$.x$1$1(Assembly.scala:24)
```

After fixing it as follows, the problem was solved.

```scala
      assemblyMergeStrategy in assembly := {
        case "META-INF\\io.netty.versions.properties" =>
          MergeStrategy.first
        case "ahc-default.properties" =>
          ahcMerge
        case x =>
          val oldStrategy = (assemblyMergeStrategy in assembly).value
          oldStrategy(x)
      },
```

Deduplicate error seems to be caused by a case leak for inability to resolve the path correctly.

**Comment by ipergenitsa** [comment]
@eed3si9n, how was this designed? As far as I know, jar paths use '/' as a separator. Does this apply here? I'd like to try to contribute to the project fixing this (in case it is a bug)

**Comment by eed3si9n** [comment]
See https://github.com/sbt/sbt-assembly#merge-strategy. The example uses `PathList(...)`.
