### ISSUE TITLE
Cannot shade java 10 class files

### ISSUE THREAD

**Issue by Jankoekenpan** [sbt/sbt-assembly#330]
```Unable to read classname from bytecode in xyz/janboerman/guilib/api/GuiInventoryHolder.class
Shading is therefore impossible, so this entry will be skipped.```

**Comment by eed3si9n** [comment]
Pants fork of Jar Jar Links has released 1.6.6 (https://github.com/pantsbuild/jarjar/releases/tag/org.pantsbuild-jarjar-1.6.6) with ASM 6.2 (https://asm.ow2.io/versions.html), so I am guessing that's what we need to bump up to.

**Comment by Jankoekenpan** [comment]
I just noticed that 16 days ago the JarJar dependency was updated to version 1.6.6. How do I use the bleeding version of sbt-assembly (as it is on GitHub right now) in my sbt-based project? I tried installing sbt-assembly into my local repository but sbt still complained about missing attributes (scalaVersion=2.12 and sbtVersion=1.0). Any ETA on when sbt-assembly 0.14.8 will be released?

**Comment by xuwei-k** [comment]
add following settings in `project/plugins.sbt` until sbt-assembly 0.14.8

```scala
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.7")

libraryDependencies += "org.pantsbuild" % "jarjar" % "1.6.6"
```

**Comment by xuwei-k** [comment]
https://github.com/sbt/sbt-assembly/releases/tag/v0.14.8

**Comment by Jannyboy11** [comment]
Thanks for updating me! I've updated the dependency to Java 11 too, but now the assembly plugin cannot read the classes because it uses Opcodes.ASM6 instead of Opcodes.ASM7. ClassVisitor#visitNestHostExperimental throws an UnsupportedOperationException when using ASM api levels lower than 7.

```
[info] Loading settings from idea.sbt ...
[info] Loading global plugins from C:\Users\Test\.sbt\1.0\plugins
[info] Loading settings from assembly.sbt ...
[info] Loading project definition from C:\Users\Test\Minecraft\workspace\RSTrade\project
[info] Loading settings from build.sbt ...
[info] Set current project to RSTrade (in build file:/C:/Users/Test/Minecraft/workspace/RSTrade/)
Waiting for lock on C:\Users\Test\.ivy2\.sbt.ivy.lock to be available...
[success] Total time: 7 s, completed 5 okt. 2018 18:57:54
Waiting for lock on C:\Users\Test\.ivy2\.sbt.ivy.lock to be available...
[info] Updating ...
[warn] The descriptor in file:/C:/Users/Test/.m2/repository/org/spigotmc/spigot/1.12.2-R0.1-SNAPSHOT/spigot-1.12.2-R0.1-SNAPSHOT.pom from Maven2 Local could not be parsed.
[warn] Choosing Maven2 Local for org.spigotmc#spigot;1.12.2-R0.1-SNAPSHOT
[warn] The descriptor in file:/C:/Users/Test/.m2/repository/org/bukkit/bukkit/1.13.1-R0.1-SNAPSHOT/bukkit-1.13.1-R0.1-SNAPSHOT.pom from Maven2 Local could not be parsed.
[warn] Choosing Maven2 Local for org.bukkit#bukkit;1.13.1-R0.1-SNAPSHOT
[info] Done updating.
[info] Compiling 28 Scala sources to C:\Users\Test\Minecraft\workspace\RSTrade\target\scala-2.12\classes ...
[WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/C:/Users/Test/.sbt/boot/scala-2.12.6/org.scala-sbt/sbt/1.1.6/protobuf-java-3.3.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
warn] there were two deprecation warnings; re-run with -deprecation for details
[warn] one warning found
[info] Done compiling.
[error] java.lang.UnsupportedOperationException
[error]         at org.objectweb.asm.ClassVisitor.visitNestHostExperimental(ClassVisitor.java:158)
[error]         at org.objectweb.asm.commons.ClassRemapper.visitNestHostExperimental(ClassRemapper.java:186)
[error]         at org.objectweb.asm.ClassReader.accept(ClassReader.java:541)
[error]         at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
[error]         at org.pantsbuild.jarjar.util.JarTransformer.process(JarTransformer.java:38)
[error]         at org.pantsbuild.jarjar.util.JarProcessorChain.process(JarProcessorChain.java:38)
[error]         at org.pantsbuild.jarjar.MainProcessor.process(MainProcessor.java:115)
[error]         at org.pantsbuild.jarjar.JJProcessor.process(JJProcessor.scala:9)
[error]         at sbtassembly.Shader$.$anonfun$shadeDirectory$7(Shader.scala:102)
[error]         at sbtassembly.Shader$.$anonfun$shadeDirectory$7$adapted(Shader.scala:97)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:944)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:944)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]         at sbtassembly.Shader$.shadeDirectory(Shader.scala:97)
[error]         at sbtassembly.Assembly$.$anonfun$assembleMappings$9(Assembly.scala:218)
[error]         at scala.collection.parallel.AugmentedIterableIterator.map2combiner(RemainsIterator.scala:112)
[error]         at scala.collection.parallel.AugmentedIterableIterator.map2combiner$(RemainsIterator.scala:109)
[error]         at scala.collection.parallel.immutable.ParVector$ParVectorIterator.map2combiner(ParVector.scala:62)
[error]         at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1052)
[error]         at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
[error]         at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
[error]         at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
[error]         at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1049)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
[error]         at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:436)
[error]         at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
[error]         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[error]         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[error]         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[error]         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[error]         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[error] (assembly / assembledMappings) java.lang.UnsupportedOperationException
[error] Total time: 80 s, completed 5 okt. 2018 18:59:14
```
