### ISSUE TITLE
assemblyMergeStrategy doesn't work for multi-project build

### ISSUE THREAD

**Issue by koertkuipers** [sbt/sbt-assembly#337]
i have a multi project build where one of the sub-projects builds an assembly jar. it "depends" on the other sub-projects (with the .dependsOn(project1, project2) syntax. the other sub-projects all create jars with a META-INF/LICENSE file. in the assembly i get this error:
```
[error] java.util.zip.ZipException: duplicate entry: META-INF/LICENSE
[error] 	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:232)
[error] 	at java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:109)
[error] 	at sbt.io.IO$.addFileEntry$1(IO.scala:550)
[error] 	at sbt.io.IO$.$anonfun$writeZip$3(IO.scala:559)
[error] 	at sbt.io.IO$.$anonfun$writeZip$3$adapted(IO.scala:559)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:944)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:944)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] 	at sbt.io.IO$.writeZip(IO.scala:559)
[error] 	at sbt.io.IO$.$anonfun$archive$1(IO.scala:513)
[error] 	at sbt.io.IO$.$anonfun$archive$1$adapted(IO.scala:510)
[error] 	at sbt.io.IO$.$anonfun$withZipOutput$1(IO.scala:595)
[error] 	at sbt.io.IO$.$anonfun$withZipOutput$1$adapted(IO.scala:584)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.io.IO$.withZipOutput(IO.scala:584)
[error] 	at sbt.io.IO$.archive(IO.scala:510)
[error] 	at sbt.io.IO$.jar(IO.scala:489)
[error] 	at sbt.Package$.makeJar(Package.scala:135)
[error] 	at sbtassembly.Assembly$.makeJar$1(Assembly.scala:40)
[error] 	at sbtassembly.Assembly$.$anonfun$apply$13(Assembly.scala:81)
[error] 	at sbtassembly.Assembly$.$anonfun$apply$13$adapted(Assembly.scala:77)
[error] 	at sbt.util.Tracked$.$anonfun$outputChanged$1(Tracked.scala:101)
[error] 	at sbtassembly.Assembly$.apply(Assembly.scala:85)
[error] 	at sbtassembly.Assembly$.$anonfun$assemblyTask$1(Assembly.scala:244)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by eed3si9n** [comment]
If individual subprojects are creating assembly on their own, why does this happen?
Are you rewiring packageBin to be a fat jar?

**Comment by koertkuipers** [comment]
packageBin is not a far jar

it seems to be the logic for assemblyMergeStrategy is not equipped to handle duplicates coming from other sub-projects that the project that creates the assembly jar depends on using the `dependsOn` syntax

**Comment by koertkuipers** [comment]
for example:
i have sub project A that builds an assembly and also depends on sub project B
both sub project A and sub project B have a src/main/resources/reference.conf
normally multiple reference.conf files get concatenated, but when they are from sub projects it throws an error instead

**Comment by KhankaLake** [comment]
assemblyMergeStrategy in assembly := {
    case PathList("META-INF", ps @ _*) if ps.contains("MANIFEST.MF") || ps.contains("LICENSE")
      => MergeStrategy.discard
    case "reference.conf" => MergeStrategy.concat //If you use Akka
}
