### ISSUE TITLE
Repackaging a signed jar file

### ISSUE THREAD

**Issue by odwrotnie** [sbt/sbt-assembly#34]
I get this:

```
Exception in thread "main" java.lang.SecurityException: no manifiest section for signature file entry org/bouncycastle/cms/CMSSign
edDataStreamGenerator$TeeOutputStream.class
        at sun.security.util.SignatureFileVerifier.verifySection(Unknown Source)
        at sun.security.util.SignatureFileVerifier.processImpl(Unknown Source)
        at sun.security.util.SignatureFileVerifier.process(Unknown Source)
        at java.util.jar.JarVerifier.processEntry(Unknown Source)
        at java.util.jar.JarVerifier.update(Unknown Source)
```

How do you deal with this issue?

**Comment by bluenote10** [comment]
I had a similar issue, but I was able to solve it by [this workaround](http://www.jamesswafford.com/2012/03/11/java-lang-securityexception-no-manifest-section-for-signature-file-entry/). In SBT terms, I did something similar to this:

    mergeStrategy in assembly <<= (mergeStrategy in assembly) { (old) =>
      {
        case ps if ps.endsWith(".SF") => MergeStrategy.discard
        case ps if ps.endsWith(".DSA") => MergeStrategy.discard
        case ps if ps.endsWith(".RSA") => MergeStrategy.discard
        case x => old(x)
      }
    }

**Comment by drywet** [comment]
Using `assemblyExcludedJars` setting, you can copy specific jar files to a directory with your artifact jar, which is available in `(Compile / packageBin / artifactPath).value`
