### ISSUE TITLE
Cannot shade JDK11 class files (JEP 181)

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt-assembly#343]
- https://gitlab.ow2.org/asm/asm/blob/ASM_6_2_1/asm/src/main/java/org/objectweb/asm/ClassVisitor.java#L157
- http://openjdk.java.net/jeps/181
- https://github.com/xuwei-k/sbt-assembly/commit/15409b6954195344e7903546bcf6b38346983b3a
- https://travis-ci.org/xuwei-k/sbt-assembly/builds/437428863#L1251

### project/plugins.sbt

```scala
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.8")
```
### project/build.properties

```
sbt.version=1.2.3
```

### build.sbt

```scala
scalaVersion := "2.12.7"

assemblyShadeRules in assembly := Seq(
  ShadeRule.rename("example.A" -> "example.C").inProject
)
```

### A.java

```java
package example;

public class A {
  public class B {
  }
}
```

### run `sbt assembly`

```
[info] [error] java.lang.UnsupportedOperationException
[info] [error] 	at org.objectweb.asm.ClassVisitor.visitNestHostExperimental(ClassVisitor.java:158)
[info] [error] 	at org.objectweb.asm.commons.ClassRemapper.visitNestHostExperimental(ClassRemapper.java:186)
[info] [error] 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:541)
[info] [error] 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
[info] [error] 	at org.pantsbuild.jarjar.util.JarTransformer.process(JarTransformer.java:38)
[info] [error] 	at org.pantsbuild.jarjar.util.JarProcessorChain.process(JarProcessorChain.java:38)
[info] [error] 	at org.pantsbuild.jarjar.MainProcessor.process(MainProcessor.java:115)
[info] [error] 	at org.pantsbuild.jarjar.JJProcessor.process(JJProcessor.scala:9)
[info] [error] 	at sbtassembly.Shader$.$anonfun$shadeDirectory$7(Shader.scala:102)
[info] [error] 	at sbtassembly.Shader$.$anonfun$shadeDirectory$7$adapted(Shader.scala:97)
[info] [error] 	at scala.collection.Iterator.foreach(Iterator.scala:944)
[info] [error] 	at scala.collection.Iterator.foreach$(Iterator.scala:944)
[info] [error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
[info] [error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[info] [error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[info] [error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[info] [error] 	at sbtassembly.Shader$.shadeDirectory(Shader.scala:97)
[info] [error] 	at sbtassembly.Assembly$.$anonfun$assembleMappings$8(Assembly.scala:197)
[info] [error] 	at scala.collection.parallel.AugmentedIterableIterator.map2combiner(RemainsIterator.scala:112)
[info] [error] 	at scala.collection.parallel.AugmentedIterableIterator.map2combiner$(RemainsIterator.scala:109)
[info] [error] 	at scala.collection.parallel.immutable.ParVector$ParVectorIterator.map2combiner(ParVector.scala:62)
[info] [error] 	at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1052)
[info] [error] 	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
[info] [error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[info] [error] 	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
[info] [error] 	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
[info] [error] 	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
[info] [error] 	at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1049)
[info] [error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
[info] [error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
[info] [error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:436)
[info] [error] 	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
[info] [error] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[info] [error] 	at java.base/java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:396)
[info] [error] 	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:721)
[info] [error] 	at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync(Tasks.scala:375)
[info] [error] 	at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync$(Tasks.scala:375)
[info] [error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:436)
[info] [error] 	at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult(Tasks.scala:419)
[info] [error] 	at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult$(Tasks.scala:412)
[info] [error] 	at scala.collection.parallel.ForkJoinTaskSupport.executeAndWaitResult(TaskSupport.scala:56)
[info] [error] 	at scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult(Tasks.scala:551)
[info] [error] 	at scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult$(Tasks.scala:551)
[info] [error] 	at scala.collection.parallel.ExecutionContextTaskSupport.executeAndWaitResult(TaskSupport.scala:80)
[info] [error] 	at scala.collection.parallel.ParIterableLike$ResultMapping.leaf(ParIterableLike.scala:956)
[info] [error] 	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
[info] [error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[info] [error] 	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
[info] [error] 	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
[info] [error] 	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
[info] [error] 	at scala.collection.parallel.ParIterableLike$ResultMapping.tryLeaf(ParIterableLike.scala:951)
[info] [error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
[info] [error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
[info] [error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:436)
[info] [error] 	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
[info] [error] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[info] [error] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[info] [error] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[info] [error] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[info] [error] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[info] [error] (assembly / assembledMappings) java.lang.UnsupportedOperationException
```

**Comment by xuwei-k** [comment]
- [ ] https://github.com/pantsbuild/jarjar/issues/39

**Comment by xuwei-k** [comment]
My pull request merged into jarjar https://github.com/pantsbuild/jarjar/pull/40 await jarjar 1.7.0 release https://github.com/pantsbuild/jarjar/issues/41

**Comment by eed3si9n** [comment]
Nice. Thanks for the followup.
