### ISSUE TITLE
Generating incorect byte code on scala 2.11.x - scala.reflect.ScalaLongSignature

### ISSUE THREAD

**Issue by er1c** [sbt/sbt-assembly#442]
After upgrading our `2.11.11` project from `sbt-assembly` `0.14.10` to `1.0.0` I see some bad byte code being generated.

The stacktrace is:

```
Exception in thread "main" java.lang.annotation.AnnotationFormatError: Duplicate annotation for class: interface scala.reflect.ScalaLongSignature: @scala.reflect.ScalaLongSignature(bytes=[^F^A        @t!B^A^C^Q^C9^QAB%tgV,7O^C^B^D  ^E1^Qn]:vKNT^Q!B^A^FWfb^WNY^B^A!        A^Q"D^A^C
[...]
        at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:125)
        at java.lang.Class.getAnnotations(Class.java:3446)
[...]
        at scala.reflect.runtime.JavaMirrors$JavaMirror.classToScala(JavaMirrors.scala:980)
        at scala.reflect.runtime.JavaMirrors$JavaMirror.classSymbol(JavaMirrors.scala:196)
        at scala.reflect.runtime.JavaMirrors$JavaMirror.classSymbol(JavaMirrors.scala:54)
        at k9lib.issues.Issue.getIssueCodeFromFlatJsonTag(Issue.scala:67)
[...]
```

And that’s not such strange when we decompile our `Issues.class` file:

```
@ScalaLongSignature(bytes = {
@ScalaLongSignature(bytes = 
public final class Issues {
```

This doesn't seem to be a problem on scala 2.12.x

It might be related to https://github.com/sbt/sbt-assembly/commit/660caae6e3b46b1fb8981ef80f61c18237451f24 ? @jeroentervoorde do you have any insight?

**Comment by er1c** [comment]
Fixed in https://github.com/sbt/sbt-assembly/commit/65828f33d6502345f84a383c3c14e52171b42bd8
