### ISSUE TITLE
OutOfMemoryError introduced by 1.1.0

### ISSUE THREAD

**Issue by cchantep** [sbt/sbt-assembly#463]
After upgrade, it seems that 1.1.0 introduce an OOM.

```
java.lang.OutOfMemoryError: Java heap space
	at java.nio.file.Files.read(Files.java:3099)
	at java.nio.file.Files.readAllBytes(Files.java:3158)
	at com.eed3si9n.jarjarabrams.Shader$.$anonfun$shadeDirectory$3(Shader.scala:19)
	at com.eed3si9n.jarjarabrams.Shader$$$Lambda$21105/548814501.apply(Unknown Source)
	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:935)
	at scala.collection.TraversableLike$WithFilter$$Lambda$2356/303559000.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:934)
	at com.eed3si9n.jarjarabrams.Shader$.shadeDirectory(Shader.scala:17)
	at sbtassembly.Assembly$.$anonfun$assembleMappings$11(Assembly.scala:296)
	at sbtassembly.Assembly$$$Lambda$21137/2147246401.apply(Unknown Source)
java.lang.OutOfMemoryError: Java heap space
	at java.nio.file.Files.read(Files.java:3099)
	at java.nio.file.Files.readAllBytes(Files.java:3158)
	at com.eed3si9n.jarjarabrams.Shader$.$anonfun$shadeDirectory$3(Shader.scala:19)
	at com.eed3si9n.jarjarabrams.Shader$$$Lambda$7588/835341038.apply(Unknown Source)
	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:935)
	at scala.collection.TraversableLike$WithFilter$$Lambda$1791/1673916398.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:934)
	at com.eed3si9n.jarjarabrams.Shader$.shadeDirectory(Shader.scala:17)
	at sbtassembly.Assembly$.$anonfun$assembleMappings$11(Assembly.scala:294)
	at sbtassembly.Assembly$$$Lambda$7624/419698892.apply(Unknown Source)
	at scala.collection.parallel.AugmentedIterableIterator.map2combiner(RemainsIterator.scala:116)
	at scala.collection.parallel.AugmentedIterableIterator.map2combiner$(RemainsIterator.scala:113)
	at scala.collection.parallel.immutable.ParVector$ParVectorIterator.map2combiner(ParVector.scala:66)
	at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1064)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
	at scala.collection.parallel.Task$$Lambda$2644/1917338662.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
	at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1061)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:160)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
[error] [launcher] error during sbt launcher: java.lang.OutOfMemoryError: Java heap space
```

- sbt 1.6.2
- JDK 1.8 (linux | osx)

**Comment by cchantep** [comment]
May be related to #454

**Comment by maziyarpanahi** [comment]
@cchantep do you still have this issue in `1.2.0`? I've noticed the same thing going from `1.2.0` to `2.0.0`, suddenly uses twice more Java heap memory. (from 3G up to 7G)

**Comment by cchantep** [comment]
Still issues with latest 2.1.1 :

```
[warn] multiple main classes detected: run 'show discoveredMainClasses' to see the list
[warn] In the last 10 seconds, 5.314 (53,5%) were spent in GC. [Heap: 0,28GB free of 0,89GB, max 0,89GB] Consider increasing the JVM heap using `-Xmx` or try a different collector, e.g. `-XX:+UseG1GC`, for better performance.
[warn] In the last 10 seconds, 8.544 (86,3%) were spent in GC. [Heap: 0,15GB free of 0,89GB, max 0,89GB] Consider increasing the JVM heap using `-Xmx` or try a different collector, e.g. `-XX:+UseG1GC`, for better performance.
[warn] In the last 10 seconds, 11.103 (114,2%) were spent in GC. [Heap: 0,15GB free of 0,89GB, max 0,89GB] Consider increasing the JVM heap using `-Xmx` or try a different collector, e.g. `-XX:+UseG1GC`, for better performance.
[warn] In the last 8 seconds, 6.304 (83,7%) were spent in GC. [Heap: 0,13GB free of 0,89GB, max 0,89GB] Consider increasing the JVM heap using `-Xmx` or try a different collector, e.g. `-XX:+UseG1GC`, for better performance.
[warn] In the last 10 seconds, 8.861 (91,5%) were spent in GC. [Heap: 0,12GB free of 0,89GB, max 0,89GB] Consider increasing the JVM heap using `-Xmx` or try a different collector, e.g. `-XX:+UseG1GC`, for better performance.
[warn] In the last 10 seconds, 8.841 (95,5%) were spent in GC. [Heap: 0,19GB free of 0,89GB, max 0,89GB] Consider increasing the JVM heap using `-Xmx` or try a different collector, e.g. `-XX:+UseG1GC`, for better performance.
[warn] In the last 10 seconds, 8.022 (80,7%) were spent in GC. [Heap: 0,15GB free of 0,89GB, max 0,89GB] Consider increasing the JVM heap using `-Xmx` or try a different collector, e.g. `-XX:+UseG1GC`, for better performance.
[warn] In the last 10 seconds, 7.704 (77,7%) were spent in GC. [Heap: 0,14GB free of 0,89GB, max 0,89GB] Consider increasing the JVM heap using `-Xmx` or try a different collector, e.g. `-XX:+UseG1GC`, for better performance.
[error] stack trace is suppressed; run last assembly for the full output
[error] (assembly) java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Self-suppression not permitted
[error] Total time: 195 s (03:15), completed 2 juil. 2023 17:05:25
```
