### ISSUE TITLE
java.util.zip.ZipException: duplicate entry: META-INF/MANIFEST.MF

### ISSUE THREAD

**Issue by darkfrog26** [sbt/sbt-assembly#80]
I have successfully been using sbt-assembly in my project for months now and recently it started complaining about duplicate entries for a couple classes after I added a couple of new dependencies.  As a result I added the following to my build:

``` scala
  mergeStrategy in assembly <<= (mergeStrategy in assembly) {
      case old => {
        case PathList("javax", "xml", xs @ _*) => MergeStrategy.first
        case PathList("org", "w3c", "dom", "TypeInfo.class") => MergeStrategy.first
        case x => old(x)
      }
    }
```

This gets me past these errors into the final building stages of my combined JAR but ultimately fails with the following:

``` scala
java.util.zip.ZipException: duplicate entry: META-INF/MANIFEST.MF
    at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:215)
    at java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:109)
    at sbt.IO$.addFileEntry$1(IO.scala:441)
    at sbt.IO$$anonfun$sbt$IO$$writeZip$2.apply(IO.scala:450)
    at sbt.IO$$anonfun$sbt$IO$$writeZip$2.apply(IO.scala:450)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:60)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at sbt.IO$.sbt$IO$$writeZip(IO.scala:450)
    at sbt.IO$$anonfun$archive$1.apply(IO.scala:403)
    at sbt.IO$$anonfun$archive$1.apply(IO.scala:401)
    at sbt.IO$$anonfun$withZipOutput$1.apply(IO.scala:496)
    at sbt.IO$$anonfun$withZipOutput$1.apply(IO.scala:482)
    at sbt.Using.apply(Using.scala:25)
    at sbt.IO$.withZipOutput(IO.scala:482)
    at sbt.IO$.archive(IO.scala:401)
    at sbt.IO$.jar(IO.scala:384)
    at sbt.Package$.makeJar(Package.scala:107)
    at sbt.Package$$anonfun$3$$anonfun$apply$3.apply(Package.scala:72)
    at sbt.Package$$anonfun$3$$anonfun$apply$3.apply(Package.scala:70)
    at sbt.Tracked$$anonfun$outputChanged$1.apply(Tracked.scala:57)
    at sbt.Tracked$$anonfun$outputChanged$1.apply(Tracked.scala:52)
    at sbt.Package$.apply(Package.scala:80)
    at sbtassembly.Plugin$Assembly$.makeJar$1(Plugin.scala:159)
    at sbtassembly.Plugin$Assembly$.apply(Plugin.scala:175)
    at sbtassembly.Plugin$.sbtassembly$Plugin$$assemblyTask(Plugin.scala:144)
    at sbtassembly.Plugin$$anonfun$baseAssemblySettings$5.apply(Plugin.scala:332)
    at sbtassembly.Plugin$$anonfun$baseAssemblySettings$5.apply(Plugin.scala:331)
    at sbt.Scoped$$anonfun$hf9$1.apply(Structure.scala:585)
    at sbt.Scoped$$anonfun$hf9$1.apply(Structure.scala:585)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
    at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
    at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:41)
    at sbt.std.Transform$$anon$5.work(System.scala:71)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:238)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
[error] (site/*:assembly) java.util.zip.ZipException: duplicate entry: META-INF/MANIFEST.MF
```

As I understand it this shouldn't happen considering the default operation of dealing with MANIFEST.MF has worked successfully for me all along and my above additions should still be activating that.  I've tried adding to my merge strategy:

``` scala
case PathList("META-INF", "MANIFEST.MF") => MergeStrategy.first
```

But I still end up with the same error.  In fact I've tried nearly every merge strategy and all fail except "discard".  If I use "discard" though then the Main-Class is not set on my resulting combined JAR.

**Comment by 506764932** [comment]
YES case PathList("META-INF", "MANIFEST.MF") => MergeStrategy.discard  trick.

**Comment by sokrahta** [comment]
*always* fallback to the old merge strategy, as shown in the [README](https://github.com/sbt/sbt-assembly/blob/master/README.md#merge-strategy) code sample

```
assemblyMergeStrategy in assembly := {
  case PathList("javax", "servlet", xs @ _*)         => MergeStrategy.first
  case PathList(ps @ _*) if ps.last endsWith ".html" => MergeStrategy.first
  case "application.conf"                            => MergeStrategy.concat
  case "unwanted.txt"                                => MergeStrategy.discard
  case x =>
    val oldStrategy = (assemblyMergeStrategy in assembly).value
    oldStrategy(x)
}
```

**Comment by emwalker** [comment]
Thank you random internet person who suggested `MergeStrategy.discard`.

**Comment by marcos-sb** [comment]
Thanks! Solved my problem as well.

**Comment by ariasf** [comment]
case PathList("META-INF", "MANIFEST.MF") => MergeStrategy.discard  FTW

**Comment by akonopko** [comment]
thanks people

**Comment by vikram9r** [comment]
Thank you random internet person for suggesting MergeStrategy.discard

**Comment by sguzman** [comment]
i love this thread. 1+ from me as well since it worked

**Comment by evandertino** [comment]
Thank you guys

**Comment by eed3si9n** [comment]
If you fallback to the old strategy discarding should be there already:

```scala
assemblyMergeStrategy in assembly := {
  case PathList("javax", "servlet", xs @ _*)         => MergeStrategy.first
  // your other customization

  case x =>
    val oldStrategy = (assemblyMergeStrategy in assembly).value
    oldStrategy(x)
}
```
